# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."contact-sync" = {
    image = "bleala/vdirsyncer:2.6.1@sha256:cbe4a492453b597fdeef996a7e1555c8da9208307efb2ec1e4a059cda6123b3d";
    environment = {
      "AUTODISCOVER" = "false";
      "AUTOSYNC" = "true";
      "AUTOUPDATE" = "false";
      "CRON_TIME" = "*/15 * * * *";
      "PRE_SYNC_SCRIPT_FILE" = "/vdirsyncer/require-enabled.sh";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/run/onepassword-secrets/vdirsyncerGoogleClientId:/vdirsyncer/secrets/google-client-id:ro"
      "/run/onepassword-secrets/vdirsyncerGoogleClientSecret:/vdirsyncer/secrets/google-client-secret:ro"
      "/run/onepassword-secrets/vdirsyncerIcloudAppPassword:/vdirsyncer/secrets/icloud-app-password:ro"
      "/run/onepassword-secrets/vdirsyncerIcloudUsername:/vdirsyncer/secrets/icloud-username:ro"
      "/var/lib/electricpeak/appdata/vdirsyncer:/vdirsyncer:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=contact-sync"
      "--network=electricpeak"
    ];
  };
  systemd.services."docker-contact-sync" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-electricpeak-root.target"
    ];
    wantedBy = [
      "docker-compose-electricpeak-root.target"
    ];
  };
  virtualisation.oci-containers.containers."foodlog-sync" = {
    image = "ghcr.io/junr03/foodlog-sync:latest";
    environment = {
      "CRONOMETER_ACCOUNT_TZ" = "America/Los_Angeles";
      "CRONOMETER_PASSWORD_FILE" = "/run/secrets/cronometer-password";
      "CRONOMETER_SESSION_PATH" = "/data/cronometer-session.json";
      "CRONOMETER_USERNAME_FILE" = "/run/secrets/cronometer-username";
      "FOODLOG_DATABASE_PATH" = "/data/ledger.sqlite3";
      "FOODLOG_ENABLE_WRITES" = "false";
      "FOODLOG_RAW_DIR" = "/data/raw";
      "GOOGLE_DRIVE_FOLDER_ID_FILE" = "/run/secrets/google-drive-folder-id";
      "GOOGLE_DRIVE_TOKEN_FILE" = "/run/secrets/google-drive-token.json";
    };
    volumes = [
      "/run/onepassword-secrets/foodlogCronometerPassword:/run/secrets/cronometer-password:ro"
      "/run/onepassword-secrets/foodlogCronometerUsername:/run/secrets/cronometer-username:ro"
      "/run/onepassword-secrets/foodlogGoogleDriveFolderId:/run/secrets/google-drive-folder-id:ro"
      "/run/onepassword-secrets/foodlogGoogleDriveToken:/run/secrets/google-drive-token.json:ro"
      "/var/lib/electricpeak/appdata/foodlog-sync:/data:rw"
    ];
    cmd = [ "--poll-interval" "900" ];
    user = "1000:100";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=foodlog-sync"
      "--network=electricpeak"
    ];
  };
  systemd.services."docker-foodlog-sync" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-electricpeak-root.target"
    ];
    wantedBy = [
      "docker-compose-electricpeak-root.target"
    ];
  };
  virtualisation.oci-containers.containers."rawbackup" = {
    image = "python:3.13-alpine";
    volumes = [
      "/etc/nixos/containers/source/utilities/rawbackup/app:/app:ro"
      "/var/lib/rawbackup:/data:ro"
      "/var/lib/rawbackup/reconcile:/reconcile:rw"
    ];
    cmd = [ "python" "/app/server.py" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=rawbackup"
      "--network=electricpeak"
    ];
  };
  systemd.services."docker-rawbackup" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-electricpeak-root.target"
    ];
    wantedBy = [
      "docker-compose-electricpeak-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-electricpeak-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
