# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."grafana" = {
    image = "grafana/grafana:latest";
    environment = {
      "GF_LOG_FILTERS" = "rendering:debug";
      "GF_RENDERING_CALLBACK_URL" = "http://grafana:3000/";
      "GF_RENDERING_SERVER_URL" = "http://renderer:9081/render";
    };
    ports = [
      "3000:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=grafana"
      "--network=electricpeak"
    ];
  };
  systemd.services."docker-grafana" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-electricpeak-root.target"
    ];
    wantedBy = [
      "docker-compose-electricpeak-root.target"
    ];
  };
  virtualisation.oci-containers.containers."grafana-image-renderer" = {
    image = "grafana/grafana-image-renderer:latest";
    environment = {
      "ENABLE_METRICS" = "true";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=renderer"
      "--network=electricpeak"
    ];
  };
  systemd.services."docker-grafana-image-renderer" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-electricpeak-root.target"
    ];
    wantedBy = [
      "docker-compose-electricpeak-root.target"
    ];
  };
  virtualisation.oci-containers.containers."loki" = {
    image = "grafana/loki:latest";
    ports = [
      "3100:3100/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=loki"
      "--network=electricpeak"
    ];
  };
  systemd.services."docker-loki" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-electricpeak-root.target"
    ];
    wantedBy = [
      "docker-compose-electricpeak-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-electricpeak-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
